---

- name: Create output directory
  ansible.builtin.file:
    path: "{{ syft_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Activate logrotation
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/syft
    mode: "0644"
  register: __logrotate

- name: Execute logrotation  # noqa no-handler
  ansible.builtin.command: >
    logrotate -f /etc/logrotate.d/syft
  changed_when: true
  when: __logrotate.changed
