---

- name: Create output directory
  ansible.builtin.file:
    path: "{{ syft_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Activate logrotation
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/syft
    mode: "0644"
  notify: Logrotate
