---

- name: Include install.yml
  ansible.builtin.include_tasks: install.yml

- name: Include config.yml
  ansible.builtin.include_tasks: config.yml

- name: Include schedule.yml
  ansible.builtin.include_tasks: schedule.yml
  when: syft_schedule | bool
