---

- name: Ensure all components are present
  ansible.builtin.include_role:
    name: deitkrachten.cron

- name: Create wrapper script
  ansible.builtin.template:
    src: syft.sh.j2
    dest: "{{ syft_wrapper_script }}"
    mode: "0550"

- name: Schedule daily report
  ansible.builtin.cron:
    name: Syft SBOM
    weekday: "{{ syft_schedule_times['weekday'] }}"
    minute: "{{ syft_schedule_times['minute'] }}"
    hour: "{{ syft_schedule_times['hour'] }}"
    user: "{{ syft_execution_user }}"
    job: "{{ syft_wrapper_script }}"
    cron_file: syft

- name: Execute scheduled script immediately
  when: syft_immediate | bool
  tags: molecule-idempotence-notest
  block:

    - name: Execute script
      ansible.builtin.command:
        cmd: "{{ syft_wrapper_script }}"
      become: yes
      become_user: "{{ syft_execution_user }}"
      changed_when: true
