---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    syft_schedule: True
    syft_immediate: True
    syft_central_path: /tmp/syft
  roles:
    - deitkrachten.cron
    - deitkrachten.logrotate
  tasks:
    - name: Include role 'ansible-role-syft'
      ansible.builtin.include_role:
        name: ansible-role-syft
